/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import veri_tabanı.Veri_Tabanı_İşlemleri;
import veri_tabanı.veri_tabanı_bağlantısı;
/**
 *
 * @author emre_
 */
public class Giriş_Ekrani extends javax.swing.JFrame {
    
     veri_tabanı_bağlantısı bağlantı1=new veri_tabanı_bağlantısı(); 
     Loglama_Sistem log1=new Loglama_Sistem(); 
     
    
    /**
     * Creates new form Giriş_Ekrani
     */
   
    public Giriş_Ekrani(){
        initComponents();
       
        this.setLocationRelativeTo(null);  
                                        
        
        
        new veri_tabanı_bağlantısı(); 
     
       
         müşteriNo.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!Character.isDigit(c)) {
                    e.consume(); 
                }
            }
        });
                 }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        girişEkraniPanel = new javax.swing.JPanel();
        HosgeldinizMesaj = new javax.swing.JLabel();
        müşteriNo = new javax.swing.JTextField();
        sifreText = new javax.swing.JPasswordField();
        giriş_Buton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Sifre_Yenile = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("USKUDAR BANK GİRİŞ EKRANI");

        girişEkraniPanel.setBackground(new java.awt.Color(153, 153, 153));

        HosgeldinizMesaj.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        HosgeldinizMesaj.setForeground(new java.awt.Color(51, 102, 255));
        HosgeldinizMesaj.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HosgeldinizMesaj.setText("USKUDAR BANKA HOSGELDINIZ");

        müşteriNo.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 24)); // NOI18N
        müşteriNo.setForeground(new java.awt.Color(51, 51, 51));
        müşteriNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                müşteriNoActionPerformed(evt);
            }
        });

        sifreText.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        sifreText.setForeground(new java.awt.Color(51, 51, 51));
        sifreText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sifreTextActionPerformed(evt);
            }
        });

        giriş_Buton.setText("GİRİŞ");
        giriş_Buton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giriş_ButonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("MUSTERİ NO");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("PAROLA");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/iconlar/galatatowericon.png"))); // NOI18N

        Sifre_Yenile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/iconlar/icons8-password-48.png"))); // NOI18N
        Sifre_Yenile.setText("Şifre Yenile");
        Sifre_Yenile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sifre_Yenile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sifre_YenileMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout girişEkraniPanelLayout = new javax.swing.GroupLayout(girişEkraniPanel);
        girişEkraniPanel.setLayout(girişEkraniPanelLayout);
        girişEkraniPanelLayout.setHorizontalGroup(
            girişEkraniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, girişEkraniPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HosgeldinizMesaj, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                .addGap(128, 128, 128))
            .addGroup(girişEkraniPanelLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(girişEkraniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(girişEkraniPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sifreText, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(girişEkraniPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(müşteriNo, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(girişEkraniPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(giriş_Buton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98)
                .addComponent(Sifre_Yenile, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );
        girişEkraniPanelLayout.setVerticalGroup(
            girişEkraniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(girişEkraniPanelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(girişEkraniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(HosgeldinizMesaj, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(girişEkraniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(müşteriNo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(girişEkraniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sifreText, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(girişEkraniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(girişEkraniPanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(giriş_Buton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(46, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, girişEkraniPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Sifre_Yenile)
                        .addGap(18, 18, 18))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(girişEkraniPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(girişEkraniPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sifreTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sifreTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sifreTextActionPerformed

    private void giriş_ButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giriş_ButonActionPerformed
Veri_Tabanı_İşlemleri islem1=new Veri_Tabanı_İşlemleri(); 

       String müşteri_no = müşteriNo.getText(); 
       String parola = new String(sifreText.getPassword()); 
       boolean login_true = islem1.login(müşteri_no,parola); 
    
               
        if (login_true) {
                  Loglama_Sistem.log("");
                  Loglama_Sistem.log("************************");
    Hesap_Ekrani hesap1 = new Hesap_Ekrani(islem1); 
            setVisible(false); 
           hesap1.setVisible(true); 
          Loglama_Sistem.log(">>> Sisteme Giriş Yapıldı"); 
          Loglama_Sistem.log(">>> Giriş Yapan Müşteri No: " + müşteriNo.getText()); 
       }
        else {

           JOptionPane.showMessageDialog(this,"Giris Islemi Basarisiz :)"+"\nLutfen Tekrar Deneyin");
           System.out.println(">>>"+" "+müşteriNo.getText()+" nolu musterinin sisteme giris denemesi basarisiz oldu!");
                       Loglama_Sistem.log(">>> Giriş Denemesi Başarısız: " + müşteriNo.getText()); 

        } 
    }//GEN-LAST:event_giriş_ButonActionPerformed

    private void Sifre_YenileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sifre_YenileMouseClicked
        // TODO add your handling code here:
        Sifre_Degistir_Ekrani sifre1=new Sifre_Degistir_Ekrani(); 
        sifre1.setVisible(true);
        setVisible(false);
    
    }//GEN-LAST:event_Sifre_YenileMouseClicked

    private void müşteriNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_müşteriNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_müşteriNoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Giriş_Ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Giriş_Ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Giriş_Ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Giriş_Ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new Giriş_Ekrani().setVisible(true);
             
               
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HosgeldinizMesaj;
    private javax.swing.JLabel Sifre_Yenile;
    private javax.swing.JPanel girişEkraniPanel;
    private javax.swing.JButton giriş_Buton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField müşteriNo;
    private javax.swing.JPasswordField sifreText;
    // End of variables declaration//GEN-END:variables
}
