/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import javax.swing.JOptionPane;
import veri_tabanı.Veri_Tabanı_İşlemleri;
/**
 *
 * @author emre_
 */
public class Sifre_Degistir_Ekrani extends javax.swing.JFrame {
Veri_Tabanı_İşlemleri veri1=new Veri_Tabanı_İşlemleri();
    /**
     * Creates new form Sifre_Degistir_Ekrani
     */
    public Sifre_Degistir_Ekrani() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sifre_Degistir_Panel = new javax.swing.JPanel();
        Eski_Sifre_Label = new javax.swing.JLabel();
        Yeni_Sifre_Label1 = new javax.swing.JLabel();
        Yeni_Sifre_TekrarLabel2 = new javax.swing.JLabel();
        Eski_Şifre_PasswordField = new javax.swing.JPasswordField();
        Yeni_Şifre_PasswordField = new javax.swing.JPasswordField();
        Yeni_Şifre_Tekrar_Password_Field = new javax.swing.JPasswordField();
        Şifre_Değiştir_Buton = new javax.swing.JButton();
        Password_Değiştir_İcon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Müşter_No_Text_Field = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Sifre_Degistir_Panel.setBackground(new java.awt.Color(204, 204, 204));

        Eski_Sifre_Label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Eski_Sifre_Label.setText("Eski Şifre:");

        Yeni_Sifre_Label1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Yeni_Sifre_Label1.setText("Yeni Şifre:");

        Yeni_Sifre_TekrarLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Yeni_Sifre_TekrarLabel2.setText("Yeni Şifre Tekrar:");

        Eski_Şifre_PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eski_Şifre_PasswordFieldActionPerformed(evt);
            }
        });

        Şifre_Değiştir_Buton.setText("Şifre Değiştir");
        Şifre_Değiştir_Buton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Şifre_Değiştir_Buton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Şifre_Değiştir_ButonActionPerformed(evt);
            }
        });

        Password_Değiştir_İcon.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Password_Değiştir_İcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/iconlar/icons8-password-reset-100.png"))); // NOI18N
        Password_Değiştir_İcon.setText("ŞİFRE YENİLEME EKRANI ");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Müşteri No:");

        Müşter_No_Text_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Müşter_No_Text_FieldActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/iconlar/icons8-return-48.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Menüye Dön");

        javax.swing.GroupLayout Sifre_Degistir_PanelLayout = new javax.swing.GroupLayout(Sifre_Degistir_Panel);
        Sifre_Degistir_Panel.setLayout(Sifre_Degistir_PanelLayout);
        Sifre_Degistir_PanelLayout.setHorizontalGroup(
            Sifre_Degistir_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Sifre_Degistir_PanelLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(Sifre_Degistir_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Sifre_Degistir_PanelLayout.createSequentialGroup()
                        .addGroup(Sifre_Degistir_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Sifre_Degistir_PanelLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(Sifre_Degistir_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(Sifre_Degistir_PanelLayout.createSequentialGroup()
                                        .addGroup(Sifre_Degistir_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Yeni_Sifre_Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Eski_Sifre_Label))
                                        .addGap(13, 13, 13))))
                            .addComponent(Yeni_Sifre_TekrarLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(Sifre_Degistir_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Yeni_Şifre_Tekrar_Password_Field, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(Eski_Şifre_PasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(Yeni_Şifre_PasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(Müşter_No_Text_Field)))
                    .addComponent(Password_Değiştir_İcon))
                .addContainerGap(136, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Sifre_Degistir_PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Sifre_Degistir_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Sifre_Degistir_PanelLayout.createSequentialGroup()
                        .addComponent(Şifre_Değiştir_Buton)
                        .addGap(134, 134, 134)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Sifre_Degistir_PanelLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
        );
        Sifre_Degistir_PanelLayout.setVerticalGroup(
            Sifre_Degistir_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Sifre_Degistir_PanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Password_Değiştir_İcon)
                .addGap(32, 32, 32)
                .addGroup(Sifre_Degistir_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Müşter_No_Text_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(Sifre_Degistir_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Eski_Şifre_PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Eski_Sifre_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Sifre_Degistir_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Yeni_Şifre_PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Yeni_Sifre_Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Sifre_Degistir_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Yeni_Şifre_Tekrar_Password_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Yeni_Sifre_TekrarLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(Sifre_Degistir_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Şifre_Değiştir_Buton)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Sifre_Degistir_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Sifre_Degistir_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Şifre_Değiştir_ButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Şifre_Değiştir_ButonActionPerformed
    String müşteri_no=Müşter_No_Text_Field.getText();
    String eskiSifre = new String(Eski_Şifre_PasswordField.getPassword());
    String yeniSifre = new String(Yeni_Şifre_PasswordField.getPassword());
    String yeniSifreTekrar = new String(Yeni_Şifre_Tekrar_Password_Field.getPassword());
    Veri_Tabanı_İşlemleri veri1=new Veri_Tabanı_İşlemleri();
    if (!yeniSifre.equals(yeniSifreTekrar)) {
        JOptionPane.showMessageDialog(this, "Yeni şifreler uyuşmuyor. Lütfen tekrar deneyin.", "Hata", JOptionPane.ERROR_MESSAGE);
       Loglama_Sistem.log("\">>>\"+müşteri_no+\" No'lu Musteri sifresini yenilemek istedi. Fakat yeni sifreler uyusmadigi icin sistem kabul etmedi...");

        return;
    }

    Veri_Tabanı_İşlemleri veriTabaniIslemleri = new Veri_Tabanı_İşlemleri();

    if (veriTabaniIslemleri.login(müşteri_no, eskiSifre) ) {
    veri1.updatePasswordInDatabase(yeniSifre,müşteri_no);
       JOptionPane.showMessageDialog(this, "Şifre başarıyla değiştirildi.\nSisteme Tekrar Yeni Sifrenizle Giris Yapiniz!", "", JOptionPane.INFORMATION_MESSAGE);
       Loglama_Sistem.log(">>> "+müşteri_no+" no'lu bu musteri sifresini degistirdi....");
        Eski_Şifre_PasswordField.setText("");
        Yeni_Şifre_PasswordField.setText("");
        Yeni_Şifre_Tekrar_Password_Field.setText("");
        dispose();
        Giriş_Ekrani giriş1=new Giriş_Ekrani();
        giriş1.setVisible(true);
    } else {
        JOptionPane.showMessageDialog(this, "Eski şifre yanlış. Lütfen tekrar deneyin.", "Hata", JOptionPane.ERROR_MESSAGE);
        Loglama_Sistem.log("\">>>\"+müşteri_no+\" no'lu musteri eski sifresini yanlis girdi...\"");
    }

    }//GEN-LAST:event_Şifre_Değiştir_ButonActionPerformed

    private void Eski_Şifre_PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eski_Şifre_PasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Eski_Şifre_PasswordFieldActionPerformed

    private void Müşter_No_Text_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Müşter_No_Text_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Müşter_No_Text_FieldActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
    Giriş_Ekrani giris1=new Giriş_Ekrani();
    giris1.setVisible(true);
    dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sifre_Degistir_Ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sifre_Degistir_Ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sifre_Degistir_Ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sifre_Degistir_Ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() { 
                new Sifre_Degistir_Ekrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Eski_Sifre_Label;
    private javax.swing.JPasswordField Eski_Şifre_PasswordField;
    private javax.swing.JTextField Müşter_No_Text_Field;
    private javax.swing.JLabel Password_Değiştir_İcon;
    private javax.swing.JPanel Sifre_Degistir_Panel;
    private javax.swing.JLabel Yeni_Sifre_Label1;
    private javax.swing.JLabel Yeni_Sifre_TekrarLabel2;
    private javax.swing.JPasswordField Yeni_Şifre_PasswordField;
    private javax.swing.JPasswordField Yeni_Şifre_Tekrar_Password_Field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton Şifre_Değiştir_Buton;
    // End of variables declaration//GEN-END:variables
}
